# theme used
remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"

title: RAPIDS Docs
description: RAPIDS demo, process, and technical documentation.
baseurl: "/docs/" # the subpath of your site, e.g. /blog

permalink: pretty
exclude: ["README.md"]

aux_links:
    "View Docs on GitHub":
      - "https://github.com/rapidsai/devdocs"

# Enable or disable the site search
search_enabled: true
