# theme used
remote_theme: pmarsceill/just-the-docs

title: RAPIDS Dev Docs
description: Developer docs of processes and standards followed by RAPIDS
baseurl: "/devdocs/" # the subpath of your site, e.g. /blog

permalink: pretty
exclude: ["README.md"]

aux_links:
    "View RAPIDS Dev Docs on GitHub":
      - "https://github.com/rapidsai/devdocs"

# Enable or disable the site search
search_enabled: true
